import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import type { BodyId, Experiment, Frame, Profile, SimulationResult } from '../types';
import { getWeaponProfile, getArmorProfile } from '../physics/geometry';
import { getInitialPoses } from '../physics/scene';

export interface ViewportHandle { screenshot:()=>string|undefined; setView:(view:'iso'|'top'|'side')=>void }
interface Props { config:Experiment; frame?:Frame; result:SimulationResult|null; showPaths:boolean; showContacts:boolean; showDimensions:boolean }
function extrusion(profile:Profile,depth:number){const shape=new THREE.Shape(profile.outer.map(p=>new THREE.Vector2(...p)));shape.holes=profile.holes.map(h=>new THREE.Path(h.map(p=>new THREE.Vector2(...p))));const geo=new THREE.ExtrudeGeometry(shape,{depth,bevelEnabled:false,steps:1,curveSegments:32});geo.translate(0,0,-depth/2);geo.computeVertexNormals();return geo}
export default forwardRef<ViewportHandle,Props>(function SceneViewport({config,frame,result,showPaths,showContacts,showDimensions},ref){
 const mount=useRef<HTMLDivElement>(null);const cameraView=useRef<'iso'|'top'|'side'>('iso');const api=useRef<{renderer:THREE.WebGLRenderer;camera:THREE.PerspectiveCamera;scene:THREE.Scene;controls:OrbitControls;groups:Partial<Record<BodyId,THREE.Group>>;contact:THREE.Group;paths:THREE.Group}|null>(null);const [error,setError]=useState('');
 const setView=(view:'iso'|'top'|'side')=>{cameraView.current=view;const a=api.current;if(!a)return;const bounds=new THREE.Box3();Object.values(a.groups).forEach(g=>{if(g)bounds.expandByObject(g)});const center=bounds.isEmpty()?new THREE.Vector3(0,.075,0):bounds.getCenter(new THREE.Vector3());const size=bounds.getSize(new THREE.Vector3());const distance=Math.max(1,1.6/a.camera.aspect)*Math.max(.75,size.length()/.65);a.controls.maxDistance=Math.max(3,distance*3);a.controls.target.copy(center);a.camera.up.set(0,1,0);if(view==='top'){a.camera.position.set(0,1.03,.001);a.camera.up.set(0,0,-1)}else if(view==='side')a.camera.position.set(0,.16,.95);else a.camera.position.set(-.62,.49,.64);a.camera.position.multiplyScalar(distance).add(center);a.camera.lookAt(center);a.controls.update()};
 useImperativeHandle(ref,()=>({screenshot:()=>{const a=api.current;if(!a)return;a.renderer.render(a.scene,a.camera);return a.renderer.domElement.toDataURL('image/png')},setView}));
 useEffect(()=>{if(!mount.current)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});}catch{setError('当前浏览器无法启用三维显示。请启用硬件加速，或换用支持 WebGL 的浏览器。');return}
  setError('');renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setClearColor('#15252e');renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;renderer.domElement.setAttribute('aria-label','三维碰撞视口，可拖动旋转、滚轮缩放');mount.current.appendChild(renderer.domElement);
  const scene=new THREE.Scene();scene.fog=new THREE.Fog('#15252e',2.4,5);const camera=new THREE.PerspectiveCamera(39,1,.002,20);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.2;controls.maxDistance=3;controls.maxPolarAngle=Math.PI*.49;controls.target.set(0,.075,0);camera.position.set(-.62,.49,.64);controls.update();
  scene.add(new THREE.HemisphereLight('#deefff','#32454f',2));const light=new THREE.DirectionalLight('#ffffff',4);light.position.set(-.4,1.2,.6);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-1,right:1,top:1,bottom:-1,near:.1,far:4});light.shadow.bias=-.0002;light.shadow.normalBias=.002;scene.add(light);const rim=new THREE.DirectionalLight('#a4ddff',1.5);rim.position.set(.8,.4,-1);scene.add(rim);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(8,8),new THREE.MeshStandardMaterial({color:'#1b2e38',roughness:.88,metalness:.15}));floor.rotation.x=-Math.PI/2;floor.position.y=-.001;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(4,40,'#435760','#2b404b');grid.position.y=.0002;scene.add(grid);
  const groups:Partial<Record<BodyId,THREE.Group>>={};const sideColor={a:0x4ca7ee,b:0xef9e59};const add=(id:BodyId,geo:THREE.BufferGeometry,color:number,metal=.4)=>{const group=new THREE.Group();const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,metalness:metal,roughness:.36,side:THREE.DoubleSide}));mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geo,25),new THREE.LineBasicMaterial({color:color===0xb4c8cf?0xe2f2f8:color,transparent:true,opacity:.68}));group.add(edges);groups[id]=group;scene.add(group);return group};
  const chassis=(side:'a'|'b')=>{const r=config[side].robot;const g=add(`${side}Chassis`,new THREE.BoxGeometry(r.length,r.height,r.width),side==='a'?0x264a60:0x62452f,.28);const trim=new THREE.Mesh(new THREE.BoxGeometry(r.length*.82,.001,r.width*.7),new THREE.MeshStandardMaterial({color:sideColor[side],roughness:.6,metalness:.4}));trim.position.y=r.height/2+.0007;g.add(trim);const line=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(r.length,r.height,r.width)),new THREE.LineBasicMaterial({color:sideColor[side]}));g.add(line)};
  const weapon=(side:'a'|'b')=>{const w=config[side].weapon;const geo=extrusion(getWeaponProfile(w),w.thickness);if(w.axis==='horizontal')geo.rotateX(-Math.PI/2);const g=add(`${side}Weapon`,geo,0xb4c8cf,.8);const origin=new THREE.Mesh(new THREE.SphereGeometry(.004,12,12),new THREE.MeshBasicMaterial({color:sideColor[side]}));g.add(origin);const axis=new THREE.ArrowHelper(new THREE.Vector3(0,w.axis==='horizontal'?1:0,w.axis==='vertical'?1:0),new THREE.Vector3(),.065,sideColor[side],.012,.005);g.add(axis)};
  try{chassis('a');weapon('a');if(config.mode==='weapon-weapon'){chassis('b');weapon('b')}else{if(config.armor.mount==='robot')chassis('b');add('bArmor',extrusion(getArmorProfile(config.armor),config.armor.width),0xcb8e5e,.6)}const poses=getInitialPoses(config);for(const [id,p]of Object.entries(poses)){const g=groups[id as BodyId];if(g){g.position.fromArray(p!.position);g.quaternion.fromArray(p!.rotation)}}}catch(e){setError(`几何暂不可显示：${e instanceof Error?e.message:'请检查尺寸'}`)}
  const jointLinks=(config.mode==='weapon-weapon'?['a','b']:['a']).map(side=>{const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineDashedMaterial({color:side==='a'?0x67b3e4:0xe4a062,dashSize:.008,gapSize:.005,transparent:true,opacity:.8,depthTest:false}));scene.add(line);return {side:side as 'a'|'b',line}});
  const updateJointLinks=()=>jointLinks.forEach(({side,line})=>{const chassis=groups[`${side}Chassis`],rotor=groups[`${side}Weapon`];if(!chassis||!rotor)return;const r=config[side].robot;const start=new THREE.Vector3((side==='a'?1:-1)*r.length/2,r.height/2,0).applyQuaternion(chassis.quaternion).add(chassis.position);const positions=line.geometry.attributes.position;positions.setXYZ(0,start.x,start.y,start.z);positions.setXYZ(1,rotor.position.x,rotor.position.y,rotor.position.z);positions.needsUpdate=true;line.geometry.computeBoundingSphere();line.computeLineDistances()});
  const contact=new THREE.Group();const paths=new THREE.Group();scene.add(contact,paths);api.current={renderer,camera,scene,controls,groups,contact,paths};setView(cameraView.current);const resize=()=>{if(!mount.current)return;const {width,height}=mount.current.getBoundingClientRect();renderer.setSize(width,Math.max(1,height));camera.aspect=width/Math.max(1,height);camera.updateProjectionMatrix();setView(cameraView.current)};const observer=new ResizeObserver(resize);observer.observe(mount.current);resize();renderer.setAnimationLoop(()=>{controls.update();updateJointLinks();renderer.render(scene,camera)});
  return()=>{observer.disconnect();renderer.setAnimationLoop(null);controls.dispose();scene.traverse(o=>{const obj=o as THREE.Mesh;if(obj.geometry)obj.geometry.dispose();if(obj.material)(Array.isArray(obj.material)?obj.material:[obj.material]).forEach(m=>m.dispose())});renderer.dispose();renderer.domElement.remove();api.current=null};
 },[config]);
 useEffect(()=>{const a=api.current;if(!a||!frame)return;Object.entries(frame.poses).forEach(([id,p])=>{const g=a.groups[id as BodyId];if(g&&p){g.position.fromArray(p.position);g.quaternion.fromArray(p.rotation)}})},[frame,config]);
 useEffect(()=>{const a=api.current;if(!a)return;const clear=(group:THREE.Group)=>{group.traverse(o=>{const obj=o as THREE.Mesh;obj.geometry?.dispose();if(obj.material)(Array.isArray(obj.material)?obj.material:[obj.material]).forEach(m=>m.dispose())});group.clear()};clear(a.paths);if(!showPaths||!result)return;for(const id of ['aWeapon',result.config.mode==='weapon-weapon'?'bWeapon':'bArmor'] as BodyId[]){const pts=result.frames.map(f=>f.poses[id]?.position).filter((p):p is [number,number,number]=>!!p).map(p=>new THREE.Vector3(...p));if(pts.length>1)a.paths.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:id.startsWith('a')?0x58b5ff:0xffac6c,transparent:true,opacity:.5}))) }},[result,showPaths,config]);
 useEffect(()=>{const a=api.current;if(!a)return;a.contact.traverse(o=>{const m=o as THREE.Mesh;m.geometry?.dispose();if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>x.dispose())});a.contact.clear();if(!showContacts||!result)return;const t=frame?.time??0;const events=result.events.filter(e=>e.time<=t+.004&&t-e.time<.1).slice(-3);for(const e of events){const p=new THREE.Vector3(...e.point);const sphere=new THREE.Mesh(new THREE.SphereGeometry(.005,12,12),new THREE.MeshBasicMaterial({color:0xffe3a3}));sphere.position.copy(p);a.contact.add(sphere);a.contact.add(new THREE.ArrowHelper(new THREE.Vector3(...e.normal).normalize(),p,.09,0xffd282,.014,.009))}},[frame,result,showContacts,config]);
 const dimension=(p:Profile,h:number)=>{const xs=p.outer.map(v=>v[0]),ys=p.outer.map(v=>v[1]);return `${Math.round((Math.max(...xs)-Math.min(...xs))*1000)} × ${Math.round((Math.max(...ys)-Math.min(...ys))*1000)} × ${Math.round(h*1000)} mm`};
 return <div className="viewport"><div className="three-mount" ref={mount}/>{error&&<div className="viewport-error">{error}</div>}<div className="viewport-corner"><span className="live-dot"/>三维实验场<span className="dim-text">刚体模型 · L1 · 虚线为连接示意</span></div><div className="viewport-compass"><span className="y">Y</span><span className="z">Z</span><span className="x">X</span><i/></div>{showDimensions&&<div className="dimension-overlay"><div><span className="label-a">A</span> {dimension(getWeaponProfile(config.a.weapon),config.a.weapon.thickness)}</div><div><span className="label-b">B</span>{config.mode==='weapon-armor'?dimension(getArmorProfile(config.armor),config.armor.width):dimension(getWeaponProfile(config.b.weapon),config.b.weapon.thickness)}</div></div>}<div className="viewport-footer"><span>网格间距 100 mm</span><span>拖动旋转 · 滚轮缩放 · 右键平移</span></div>{frame&&<div className="viewport-time"><b>{frame.time.toFixed(3)}</b><span>s</span></div>}</div>
});
