import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowRightLeft, BookOpen, Check, ChevronDown, CircleHelp, Copy, Download, FileJson, FolderOpen, Gauge, GitCompareArrows, History, Maximize2, Pause, Play, Plus, RotateCcw, Save, ScanLine, Settings2, Shield, SkipBack, SkipForward, Square, Upload, X, Zap } from 'lucide-react';
import { DEFAULT_EXPERIMENT, cloneExperiment } from './defaults';
import type { Experiment, Frame, SimulationResult, Profile, Vec2, DrawingImage } from './types';
import { armorMassProperties, getArmorProfile, getWeaponProfile, rpmAtStart, validateExperiment, weaponMassProperties } from './physics/geometry';
import { ArmorPanel, NumberField, WeaponPanel } from './components/ParameterPanel';
import SceneViewport, { type ViewportHandle } from './components/SceneViewport';
import ProfileEditor from './components/ProfileEditor';
import ResultsPanel from './components/ResultsPanel';
import { exportCSV, exportProject, exportReport, parseProject } from './exports';
import { createExperimentId, loadExperiments, removeExperiment, saveExperiment, type SavedExperiment } from './storage';
import { REFERENCE_CASES } from './referenceCases';
const num=(n:number,d=1)=>Number.isFinite(n)?n.toLocaleString('zh-CN',{maximumFractionDigits:d}):'—';
function closestFrame(frames:Frame[],t:number){let l=0,r=frames.length-1;while(l<r){const m=Math.ceil((l+r)/2);if(frames[m].time<=t)l=m;else r=m-1}return frames[l]}

export default function App(){
 const [config,setConfig]=useState<Experiment>(()=>cloneExperiment(DEFAULT_EXPERIMENT));const [result,setResult]=useState<SimulationResult|null>(null);const [baseline,setBaseline]=useState<SimulationResult|null>(null);const [time,setTime]=useState(0);const [playing,setPlaying]=useState(false);const [rate,setRate]=useState(.25);const [busy,setBusy]=useState(false);const [progress,setProgress]=useState(0);const [toast,setToast]=useState('');const [error,setError]=useState('');const [dialog,setDialog]=useState<'settings'|'history'|'cases'|null>(null);const [editing,setEditing]=useState<'a'|'b'|'armor'|null>(null);const [exportMenu,setExportMenu]=useState(false);const [showPaths,setShowPaths]=useState(false);const [showContacts,setShowContacts]=useState(true);const [showDimensions,setShowDimensions]=useState(true);const [saved,setSaved]=useState<SavedExperiment[]>([]);const [savedId,setSavedId]=useState<string|null>(null);const [view,setView]=useState<'iso'|'top'|'side'>('iso');
 const configRef=useRef(config);configRef.current=config;const worker=useRef<Worker|null>(null);const viewport=useRef<ViewportHandle>(null);const importInput=useRef<HTMLInputElement>(null);const version=JSON.stringify(config);const stale=!!result&&JSON.stringify(result.config)!==version;const snapshot=result&&!stale?result.config:config;const frame=result&&!stale?closestFrame(result.frames,time):undefined;const duration=result?.frames.at(-1)?.time??config.settings.duration;
 const issues=useMemo(()=>{try{return validateExperiment(config)}catch{return [{path:'config',message:'配置不完整，请重新导入有效工程或恢复示例。',level:'error' as const}]}},[version]);const hardErrors=issues.filter(i=>i.level==='error');
 const properties=useMemo(()=>{try{return {a:weaponMassProperties(config.a.weapon),b:config.mode==='weapon-weapon'?weaponMassProperties(config.b.weapon):armorMassProperties(config.armor)}}catch{return null}},[version]);const rpm=frame?.rpmA??rpmAtStart(config.a.weapon);const omega=rpmAtStart(config.a.weapon)*Math.PI/30;const energy=frame?.rotationalA??.5*(properties?.a.axisInertia??0)*omega*omega;
 useEffect(()=>()=>worker.current?.terminate(),[]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t)},[toast]);useEffect(()=>{setPlaying(false)},[version]);
 useEffect(()=>{if(!playing||!result||stale)return;let handle=0,previous=performance.now();const tick=(now:number)=>{const dt=Math.min((now-previous)/1000,.1)*rate;previous=now;setTime(t=>{if(t+dt>=duration){setPlaying(false);return duration}return t+dt});handle=requestAnimationFrame(tick)};handle=requestAnimationFrame(tick);return()=>cancelAnimationFrame(handle)},[playing,result,rate,duration,stale]);
 useEffect(()=>{if(!dialog)return;const previous=document.activeElement as HTMLElement|null;const modal=document.querySelector<HTMLElement>('.modal');const selector='button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href],[tabindex="0"]';modal?.querySelector<HTMLElement>(selector)?.focus();const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')setDialog(null);if(e.key==='Tab'&&modal){const nodes=[...modal.querySelectorAll<HTMLElement>(selector)].filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',listener);return()=>{window.removeEventListener('keydown',listener);previous?.focus()}},[dialog]);
 const update=(c:Experiment)=>{setConfig(c);setError('')};const patchSettings=(p:Partial<Experiment['settings']>)=>update({...config,settings:{...config.settings,...p}});
 function run(){if(hardErrors.length){setError(hardErrors.map(x=>x.message).join('；'));return}setError('');setBusy(true);setProgress(0);setPlaying(false);worker.current?.terminate();const w=new Worker(new URL('./physics/simulation.worker.ts',import.meta.url),{type:'module'});worker.current=w;w.onmessage=e=>{const m=e.data;if(m.type==='progress')setProgress(m.progress);if(m.type==='result'){setResult(m.result);setTime(0);setBusy(false);setProgress(1);const current=JSON.stringify(m.result.config)===JSON.stringify(configRef.current);setPlaying(current);setToast(!current?'计算完成；输入已修改，保留为上次结果':m.result.events.length?'计算完成，正在回放（含目标或地面接触）':'计算完成，未检测到有效接触');w.terminate();worker.current=null}if(m.type==='error'){setBusy(false);setError(m.message);w.terminate();worker.current=null}};w.onerror=e=>{setBusy(false);setError(e.message||'计算未能完成，请检查输入或缩短模拟时长。');w.terminate();worker.current=null};w.postMessage({type:'run',config:cloneExperiment(config)})}
 function cancel(){worker.current?.terminate();worker.current=null;setBusy(false);setToast('已取消计算，参数与上次结果已保留')}
 const seek=(t:number)=>{setTime(Math.max(0,Math.min(duration,t)));setPlaying(false)};
 async function save(){try{const id=savedId??createExperimentId();await saveExperiment({id,name:config.name,updatedAt:new Date().toISOString(),config:cloneExperiment(config),result:stale?null:result});setSavedId(id);setToast('已保存到本机浏览器，可在实验记录中恢复')}catch{setError('本机保存失败，可能存储空间不足。可以先导出 JSON 工程。')}}
 async function showHistory(){try{setSaved(await loadExperiments());setDialog('history')}catch{setError('无法读取本机实验记录。')}}
 async function importFile(file:File){try{if(file.size>40*1024*1024)throw new Error('工程文件超过 40 MB，请导入更小的工程。');const p=parseProject(await file.text());const v=validateExperiment(p.config);if(v.some(i=>i.level==='error'))throw new Error(v.filter(i=>i.level==='error').map(i=>i.message).join('；'));setConfig(p.config);setResult(p.result);setSavedId(null);setTime(0);setPlaying(false);setError('');setToast('工程已导入，参数与可用结果已恢复')}catch(e){setError(e instanceof Error?e.message:'工程导入失败')}}
 const exportPNG=()=>{const png=viewport.current?.screenshot();if(!png){setError('当前三维画面不可导出');return}const a=document.createElement('a');a.download=`${config.name}-场景.png`;a.href=png;a.click()};
 const changeMode=(mode:Experiment['mode'])=>update({...config,mode,name:mode==='weapon-armor'?'双齿竖转 × 倾斜护甲':'双齿竖转 × 环形竖转'});
 const editState=editing==='armor'?{title:'护甲剖面编辑',profile:getArmorProfile(config.armor),axisOffset:[0,0] as Vec2,image:config.armor.drawing,kind:'armor' as const}:editing?{title:`${editing.toUpperCase()} 方武器轮廓`,profile:getWeaponProfile({...config[editing].weapon,axisOffset:[0,0]}),axisOffset:config[editing].weapon.axisOffset,image:config[editing].weapon.drawing,kind:'weapon' as const}:null;
 const applyProfile=(data:{profile:Profile;axisOffset:Vec2;image?:DrawingImage})=>{if(editing==='armor')update({...config,armor:{...config.armor,shape:'custom',profile:data.profile,drawing:data.image}});else if(editing){const c=config[editing];update({...config,[editing]:{...c,weapon:{...c.weapon,shape:'custom',profile:data.profile,axisOffset:data.axisOffset,drawing:data.image}}})}setEditing(null);setToast('已应用轮廓，质量与惯量已重新计算')};
 return <><header className="app-header"><a className="brand" href="#workspace" aria-label="碰撞实验室主页"><span className="brand-icon"><ScanLine size={23}/></span><span>碰撞实验室<small>ROBOT COLLISION LAB</small></span><span className="version-badge">V1</span></a><nav className="header-nav" aria-label="工具导航"><button className="active" onClick={()=>{setDialog(null);document.getElementById('workspace')?.scrollIntoView()}}>实验台</button><button onClick={()=>setDialog('cases')}><BookOpen size={15}/>参考案例</button><button onClick={showHistory}><History size={15}/>实验记录</button></nav><div className="header-status"><span className="status-dot"/>本机计算<span className="header-divider"/><span>刚体碰撞 · L0 / L1</span></div></header>
 <main id="workspace"><div className="page-heading"><div><div className="breadcrumb">工作空间 <span>/</span> 单次碰撞实验</div><label className="experiment-name"><input aria-label="实验名称" value={config.name} onChange={e=>update({...config,name:e.target.value})}/><span className="draft-badge">{stale?'参数已修改':result?'已计算':'未运行'}</span></label></div><div className="page-actions"><button className="button subtle" onClick={()=>{update(cloneExperiment(DEFAULT_EXPERIMENT));setSavedId(null);setTime(0);setToast('已恢复示例参数')}}><RotateCcw size={15}/>恢复示例</button><button className="button" onClick={()=>importInput.current?.click()}><Upload size={15}/>导入</button><button className="button" onClick={save}><Save size={15}/>保存工程</button><div className="dropdown"><button className="button dark" aria-haspopup="menu" aria-expanded={exportMenu} onClick={()=>setExportMenu(!exportMenu)}><Download size={15}/>导出<ChevronDown size={13}/></button>{exportMenu&&<div className="dropdown-menu" role="menu"><button role="menuitem" onClick={()=>{exportProject(config,stale?null:result);setExportMenu(false)}}>JSON 工程文件</button><button role="menuitem" disabled={!result||stale} onClick={()=>{if(result)exportCSV(result);setExportMenu(false)}}>CSV 数据曲线</button><button role="menuitem" disabled={!result||stale} onClick={()=>{if(result)exportReport(result,viewport.current?.screenshot());setExportMenu(false)}}>可打印实验报告</button><button role="menuitem" onClick={()=>{exportPNG();setExportMenu(false)}}>PNG 场景截图</button></div>}</div></div></div>
 <input type="file" accept=".json,application/json" hidden ref={importInput} onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);e.target.value=''}}/>
 <div className="mode-row"><div className="segmented mode-selector"><button className={config.mode==='weapon-armor'?'active':''} onClick={()=>changeMode('weapon-armor')}><Shield size={16}/>武器 × 护甲</button><button className={config.mode==='weapon-weapon'?'active':''} onClick={()=>changeMode('weapon-weapon')}><ArrowRightLeft size={16}/>武器 × 武器</button></div><div className="mode-description"><span className="assumption-badge">模型假设可查看</span><label className="check-row quick-overlap-toggle"><input type="checkbox" aria-label="限制武器与自车体接触" checked={!config.settings.allowWeaponChassisOverlap} onChange={e=>patchSettings({allowWeaponChassisOverlap:!e.target.checked})}/>限制武器与自车体接触</label><button className="text-button" onClick={()=>setDialog('settings')}><Settings2 size={14}/>接触与求解设置</button></div></div>
 {error&&<div role="alert" className="error-banner"><InfoIcon/><div><strong>请检查后继续</strong><p>{error}</p></div><button className="icon-button" aria-label="关闭错误提示" onClick={()=>setError('')}><X size={16}/></button></div>}
 {hardErrors.length>0&&<div className="validation-banner" role="alert"><strong>请修正 {hardErrors.length} 项参数</strong><ul>{hardErrors.map((i,n)=><li key={n}>{i.path.startsWith('a.')?'A 方 · ':i.path.startsWith('b.')?'B 方 · ':i.path.startsWith('armor')?'护甲 · ':'求解 · '}{i.message}</li>)}</ul></div>}
 {stale&&<div className="stale-banner"><RotateCcw size={15}/><span>参数已修改。三维视口显示新配置，底部保留上次数据；重新运行后更新结果。</span></div>}
 <div className="metrics-row"><div className="metric"><div><span>A 武器质量</span><BoxIcon/></div><strong>{num(properties?.a.mass??NaN,3)}<small>kg</small></strong><p>由轮廓、厚度与密度计算</p></div><div className="metric"><div><span>{frame?'A 当前自旋能':'A 初始自旋储能'}</span><Zap size={16}/></div><strong>{num(energy,2)}<small>J</small></strong><p>不等于传递给目标的能量</p></div><div className="metric"><div><span>{frame?'A 当前转速':'A 实际起始转速'}</span><Gauge size={17}/></div><strong>{num(rpm,0)}<small>rpm</small></strong><p>峰值 {num(config.a.weapon.peakRpm,0)} rpm · 升速 {config.a.weapon.spinupTime} s</p></div><div className="metric"><div><span>{config.mode==='weapon-armor'?'护甲倾角 / 目标质量':'B 初始自旋储能'}</span><Shield size={17}/></div><strong>{config.mode==='weapon-armor'?num(config.armor.angleDeg,1):num(.5*(properties?.b.axisInertia??0)*(rpmAtStart(config.b.weapon)*Math.PI/30)**2,2)}<small>{config.mode==='weapon-armor'?'°':'J'}</small></strong><p>{num(properties?.b.mass??NaN,3)} kg · {config.mode==='weapon-armor'?(config.armor.mount==='fixed'?'刚性固定试件':'随 B 车移动'):'独立转动关节'}</p></div></div>
 <div className="workspace-grid"><WeaponPanel side="A" combatant={config.a} onChange={a=>update({...config,a})} onEdit={()=>setEditing('a')}/><section className="simulation-panel" aria-label="碰撞实验与回放"><div className="simulation-toolbar"><div className="view-tabs">{([{v:'iso',t:'透视'},{v:'side',t:'侧视'},{v:'top',t:'顶视'}] as const).map(x=><button key={x.v} className={view===x.v?'active':''} onClick={()=>{setView(x.v);viewport.current?.setView(x.v)}}>{x.t}</button>)}</div><div className="view-options"><button className={showDimensions?'selected':''} onClick={()=>setShowDimensions(!showDimensions)} title="尺寸标注">尺寸</button><button className={showPaths?'selected':''} onClick={()=>setShowPaths(!showPaths)} title="显示运动轨迹">轨迹</button><button className={showContacts?'selected':''} onClick={()=>setShowContacts(!showContacts)} title="显示接触点与法线">接触</button><button className="icon-button" title="重置视角" aria-label="重置视角" onClick={()=>{setView('iso');viewport.current?.setView('iso')}}><Maximize2 size={15}/></button></div></div>
 <SceneViewport ref={viewport} config={snapshot} frame={frame} result={stale?null:result} showPaths={showPaths} showContacts={showContacts} showDimensions={showDimensions}/>
 <div className="transport"><div className="timeline-labels"><span>{time.toFixed(3)} <em>s</em></span><span>{duration.toFixed(3)} s</span></div><div className="timeline-wrap"><input type="range" aria-label="碰撞回放时间" min="0" max={duration} step="0.0001" value={time} disabled={!result||stale} onChange={e=>seek(+e.target.value)}/>{!stale&&result?.events.slice(0,50).map((e,i)=><button key={i} className="event-marker" title={`第 ${i+1} 次接触 ${e.time.toFixed(4)} s`} aria-label={`跳转第${i+1}次接触`} style={{left:`${e.time/duration*100}%`}} onClick={()=>seek(e.time)}/>)}</div><div className="playback-row"><div className="playback-buttons"><button className="icon-button" aria-label="返回起点" title="返回起点" disabled={!result||stale} onClick={()=>seek(0)}><SkipBack size={16}/></button><button className="play-button" aria-label={playing?'暂停回放':'播放回放'} disabled={!result||stale} onClick={()=>{if(time>=duration)setTime(0);setPlaying(!playing)}}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button className="icon-button" aria-label="前进一帧" title="前进一帧" disabled={!result||stale} onClick={()=>{const f=result!.frames.find(f=>f.time>time+.000001);seek(f?.time??duration)}}><SkipForward size={16}/></button></div><label className="speed-select">回放 <select aria-label="回放速度" value={rate} onChange={e=>setRate(+e.target.value)}><option value="0.05">0.05×</option><option value="0.1">0.1×</option><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1">1×</option></select></label><span className="playback-hint">慢动作不改变物理时间步</span></div></div>
 <div className="run-strip"><div><strong>{busy?'正在计算碰撞…':hardErrors.length?'参数需要修正':result&&!stale?(result.summary.status==='ok'?'计算完成':'计算完成 · 需复核'):'准备就绪'}</strong><span>{busy?`${Math.round(progress*100)}% · 可随时取消`:hardErrors.length?hardErrors[0].message:`${config.settings.duration} s 模拟 · 持续前进 ${Math.min(config.settings.forwardDriveTime,config.settings.duration)} s · 摩擦 μ ${config.settings.friction} · 恢复 e ${config.settings.restitution}`}</span></div>{busy?<button className="button cancel-button" onClick={cancel}><Square size={14}/>取消计算</button>:<button className="button run-button" disabled={hardErrors.length>0} onClick={run}><Play size={16}/>{result?'重新运行':'开始碰撞'}</button>}{busy&&<div className="run-progress" style={{width:`${progress*100}%`}}/>}</div>
 <div className="simulation-note"><CircleHelp size={14}/><span>接触高亮与箭头表示接触位置及法线。本版不计算永久变形或断裂。</span></div></section>
 {config.mode==='weapon-armor'?<ArmorPanel config={config} onChange={update} onEdit={()=>setEditing('armor')}/>:<WeaponPanel side="B" combatant={config.b} onChange={b=>update({...config,b})} onEdit={()=>setEditing('b')}/>}</div>
 <div className="below-workspace"><span><Activity size={14}/> 数据与解释</span>{config.mode==='weapon-weapon'&&<button className="text-button" onClick={()=>update({...config,a:structuredClone(config.b),b:structuredClone(config.a)})}><ArrowRightLeft size={14}/>交换 A / B 参数</button>}<button className="text-button" onClick={()=>{setSavedId(null);update({...cloneExperiment(config),name:config.name+' · 副本'});setToast('已创建参数副本，可修改后重新运行')}}><Copy size={14}/>复制实验</button></div>
 <ResultsPanel config={config} result={result} time={time} onSeek={seek} stale={stale} baseline={baseline} onBaseline={()=>{if(result){setBaseline(result);setToast('已保留基线。修改一个参数并重新运行，即可比较')}}}/>
 <footer className="app-footer"><span>COLLISION LAB / 01</span><span>本地保存 · SI 单位计算 · 保留输入与求解版本</span><span>模型层级 L0 + L1</span></footer></main>
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 {editing&&editState&&<ProfileEditor {...editState} onApply={applyProfile} onClose={()=>setEditing(null)}/>}
 {dialog&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog(null)}}><section className={`modal ${dialog==='cases'?'case-modal':''}`} role="dialog" aria-modal="true" aria-label={dialog==='settings'?'接触与求解设置':dialog==='history'?'实验记录':'本地参考案例'}><div className="modal-heading"><div><span className="eyebrow">{dialog==='settings'?'EXPERIMENT SETTINGS':dialog==='history'?'LOCAL PROJECTS':'NHRL REFERENCE'}</span><h2>{dialog==='settings'?'接触与求解设置':dialog==='history'?'实验记录':'本地参考案例'}</h2></div><button className="icon-button" aria-label="关闭对话框" onClick={()=>setDialog(null)}><X size={21}/></button></div>
 {dialog==='settings'&&<><p className="field-note">接触参数为本次实验假设，随工程一起保存。更细的时间步会增加计算时间。</p><div className="settings-grid"><NumberField label="接触摩擦系数 μ" value={config.settings.friction} onChange={friction=>patchSettings({friction})} step={.05}/><NumberField label="恢复系数 e" value={config.settings.restitution} onChange={restitution=>patchSettings({restitution})} min={0} max={1} step={.05}/><NumberField label="地面摩擦系数" value={config.settings.groundFriction} onChange={groundFriction=>patchSettings({groundFriction})} step={.05}/><NumberField label="模拟时长" value={config.settings.duration} onChange={duration=>patchSettings({duration})} unit="s" min={.05} max={3} step={.05}/><NumberField label="持续前进时长" value={config.settings.forwardDriveTime} onChange={forwardDriveTime=>patchSettings({forwardDriveTime})} unit="s" min={0} max={3} step={.05} hint="碰撞期间持续施加车体前进驱动；填 0 为纯自由碰撞。"/><NumberField label="目标求解频率" value={1/config.settings.step} onChange={hz=>{if(hz>0)patchSettings({step:1/hz})}} unit="Hz" step={1000}/><NumberField label="起始表面距离" value={config.settings.startDistance} onChange={startDistance=>patchSettings({startDistance,gap:startDistance})} scale={1000} unit="mm"/><NumberField label="B 横向偏移" value={config.settings.lateralOffset} onChange={lateralOffset=>patchSettings({lateralOffset})} scale={1000} unit="mm"/><NumberField label="A 面向角度" value={config.settings.aHeadingDeg} onChange={aHeadingDeg=>patchSettings({aHeadingDeg})} unit="°" step={5}/><NumberField label="B 面向角度" value={config.settings.bHeadingDeg} onChange={bHeadingDeg=>patchSettings({bHeadingDeg})} unit="°" step={5}/><NumberField label="重力加速度" value={config.settings.gravity} onChange={gravity=>patchSettings({gravity})} unit="m/s²" step={.01}/><NumberField label="随机种子" value={config.settings.seed} onChange={seed=>patchSettings({seed})} step={1}/><label className="check-row"><input type="checkbox" checked={config.settings.randomPhase} onChange={e=>patchSettings({randomPhase:e.target.checked})}/>按种子采样初始相位</label><label className="check-row"><input type="checkbox" aria-label="限制武器与自车体接触" checked={!config.settings.allowWeaponChassisOverlap} onChange={e=>patchSettings({allowWeaponChassisOverlap:!e.target.checked})}/>限制武器与自车体接触（关闭=允许穿入）</label><label className="check-row"><input type="checkbox" aria-label="限制护甲穿入地面" checked={!config.settings.allowArmorGroundOverlap} onChange={e=>patchSettings({allowArmorGroundOverlap:!e.target.checked})}/>限制护甲穿入地面（关闭=允许完全接地）</label><label className="check-row"><input type="checkbox" aria-label="允许武器触地测试" checked={config.settings.allowWeaponGroundContact} onChange={e=>patchSettings({allowWeaponGroundContact:e.target.checked})}/>允许武器触地测试（记录武器 × 地面）</label></div><p className="info-note">三个开关彼此独立：关闭自车体限制会跳过几何拦截，但转轴仍保持连接；关闭护甲穿地限制会屏蔽护甲与地面的接触，武器仍可撞击护甲。打开武器触地测试后，地面接触会进入碰撞记录和回放。</p><p className="info-note">高速转子会自动增加子步；最终采用的时间步在“模型与来源”中显示。相同种子与同一版本用于复现。</p><div className="modal-actions"><button className="button dark" onClick={()=>setDialog(null)}>完成设置</button></div></>}
 {dialog==='history'&&<>{saved.length===0?<div className="panel-empty"><FolderOpen size={32}/><h3>还没有保存的实验</h3><p>点击工作台右上角“保存工程”，下次可从这里恢复。</p></div>:<div className="saved-list">{saved.map(s=><article key={s.id}><div><h3>{s.name}</h3><p>{new Date(s.updatedAt).toLocaleString('zh-CN')} · {s.config.mode==='weapon-armor'?'武器 × 护甲':'武器 × 武器'} · {s.result?'含计算结果':'参数工程'}</p></div><button className="button" onClick={()=>{setConfig(structuredClone(s.config));setResult(s.result);setSavedId(s.id);setTime(0);setPlaying(false);setDialog(null);setError('');setToast('已恢复保存的实验')}}>打开</button><button className="text-button danger" onClick={async()=>{await removeExperiment(s.id);setSaved(await loadExperiments());setToast('已删除该条本机记录')}}>删除</button></article>)}</div>}<p className="field-note">记录保存在当前浏览器的本机数据库。导出 JSON 可备份或转移到另一台电脑。</p></>}
 {dialog==='cases'&&<><p className="field-note">来自你的 NHRL 中文知识库（2026-09-03 快照）。下列为结构参考，缺失参数不能自动变成真实仿真预设。</p><div className="case-grid">{REFERENCE_CASES.map(c=><article key={c.id}><div className="case-image"><img src={c.image} alt={`${c.name}机器人参考照片`} loading="lazy"/></div><div className="case-body"><span className="case-weight">{c.weightClass}</span><h3>{c.name}</h3><p>{c.weapon}</p><p className="field-note">{c.note}</p><div className="missing"><strong>仍需补充</strong><span>{c.missing.join('、')}</span></div><a href={c.source} target="_blank" rel="noreferrer">查看原始资料 ↗</a></div></article>)}</div><p className="field-note">图片版权归原作者，资料条目的来源与许可随知识库保留；本页仅在本地使用。</p></>}
 </section></div>}
 </>
}
function InfoIcon(){return <CircleHelp size={21}/>}
function BoxIcon(){return <ScanLine size={17}/>}
